### PR TITLE
Update input-output.md

### PR DESCRIPTION
**Pull request by ArshadAriff**
Sir any more changes?

### CODE REVIEW

**Comment by jcubic** [comment]
Looks good

**Comment by jcubic** [comment]
Do you do this for Hacktoberfest that is ending today? Do you need anything, like a label?

**Comment by ArshadAriff** [comment]
Im not sure sir i need 3 more PRs sir can you help guiding me!

**Comment by ArshadAriff** [comment]
@jcubic sir!
any more tasks i can do to be merged before today sir. This would be really helpful to me .

**Comment by jcubic** [comment]
There has to be more files to fix, you only changed one file. The problem I was talking about in the issue was not fixed at all.

You can check all the md files for grammar mistakes.

I don't know what are the rules for the PR to get accepted, that's why I asked.

**Comment by ArshadAriff** [comment]
ok sure ill look for frammer mistakes!!

**Comment by jcubic** [comment]
But as I said I used language tool extension to fix all the grammar mistakes, so it may be hard to find any. The "an" an "a" I was talking about in the issue is still there, I did not fix this issue. Only found it and assume that there are more of them.

**Comment by ArshadAriff** [comment]
@jcubic sir i found some more corrections sir ,can you merge it for HacktoberFest

**Pull request merged**
